### ISSUE TITLE
build.ninja

### ISSUE THREAD

**Issue by Trigger-broom-289** [rlancaste/kstars-on-osx-craft#1]
Hello Rob,

I've used the following command to start the build:
~/Projects/kstars-on-osx-craft/build-kstars.sh -d

And at some point I get the following error:

-- Found ZLIB: /Users/heidenrod/AstroRoot/kstars-craft/lib/libz.dylib (found version "1.2.11")
-- Found CFITSIO 3.45: /Users/heidenrod/AstroRoot/kstars-craft/lib/libcfitsio.dylib
-- Found CFITSIO: /Users/heidenrod/AstroRoot/kstars-craft/lib/libcfitsio.dylib
-- Found NOVA: /Users/heidenrod/AstroRoot/kstars-craft/lib/libnova.dylib
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Found USB1: /Users/heidenrod/AstroRoot/kstars-craft/lib/libusb-1.0.dylib
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME - Success
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.54.0")
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Found GSL: /Users/heidenrod/AstroRoot/kstars-craft/include (found version "2.2.1")
-- Found JPEG: /Users/heidenrod/AstroRoot/kstars-craft/lib/libjpeg.a
CMake Error at /Users/heidenrod/AstroRoot/kstars-craft/download/git/libs/indiserver/cmake_modules/FindFFTW3.cmake:46 (message):
  FFTW3 not found.  Please install libfftw3-dev
Call Stack (most recent call first):
  CMakeLists.txt:298 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/heidenrod/AstroRoot/kstars-craft/build/libs/indiserver/work/RelWithDebInfo-Latest/CMakeFiles/CMakeOutput.log".
executing command: "/Users/heidenrod/AstroRoot/kstars-craft/dev-utils/bin/ninja"
**ninja: error: loading 'build.ninja': No such file or directory**
Action: compile for libs/indiserver:Latest FAILED
*** Craft all failed: libs/indiserver after 2 minutes 7 seconds ***
fatal error: package libs/indiserver all failed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Trigger-broom-289** [comment]
The issue wasn't with ninja but with the missing FFTW.
I have semi-resolved it with:
brew install fftw

but now I'm getting:
fftw3.x missing

**Comment by Trigger-broom-289** [comment]
I meant to write: fftw3.h missing and not fftw3.x

**Comment by rlancaste** [comment]
FFTW is required for libdspau which currently is not building due to other issues,  I can disable that for now.  Installing with home-brew is not the best solution but sometimes will work.

**Comment by rlancaste** [comment]
ok I commented it out in my craft-blueprints try it now

**Comment by rlancaste** [comment]
Ok, that was wrong.  I actually needed to add it as a requirement to the INDIServer recipe, not take it out of the others.  It is a build requirement

**Comment by rlancaste** [comment]
This seems to have fixed the issue!!
