### ISSUE TITLE
python@3.10 bad CPU type in executable

### ISSUE THREAD

**Issue by JerryBlack** [rlancaste/kstars-on-osx-craft#11]
Almost certainly an issue with my installation, but with little knowledge of craft, this seems intractable to me...

j@Mac-Studio kstars-on-osx-craft % ~/Projects/kstars-on-osx-craft/build-kstars.sh -v

ANNOUNCE           = Nope
STABLE_BUILD       = Nope
GENERATE_DMG       = Nope
GENERATE_XCODE     = Nope
FORCE_RUN          = Nope
REMOVE_ALL         = Nope
VERBOSE            = -vvv

Script is up-to-date

DIR                   is [/Users/j/Projects/kstars-on-osx-craft]
ASTRO_ROOT            is [/Users/j/AstroRoot]
INDI_DIR              is [/Users/j/AstroRoot/indi-work]
FORKED_INDI_REPO      is [git@github.com:rlancaste/indi.git]
FORKED_INDI_3RDPARTY_REPO     is [git@github.com:rlancaste/indi-3rdparty.git]
CRAFT_DIR             is [/Users/j/AstroRoot/craft-root]
SHORTCUTS_DIR         is [/Users/j/AstroRoot/craft-shortcuts]
PATH                  is [/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin]
OSX Deployment target is [10.15]
KStars Version        is [3.6.2]
INDI_WEB_MANAGER_VERSION        is [1.8]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Checking Connections
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Homebrew connection was found.
Craft connection was found.
Oxygen connection was found.
CustomMacBlueprints connection was found.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Starting script, building INDI and KStars with Craft
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Installing Homebrew Dependencies.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
hermit                        kubefirst                     metals                        oauth2c                       zf

Warning: python@3.10 3.10.8 is already installed and up-to-date.
To reinstall 3.10.8, run:
  brew reinstall python@3.10
Warning: ninja 1.11.1 is already installed and up-to-date.
To reinstall 1.11.1, run:
  brew reinstall ninja
Warning: gnupg 2.3.8 is already installed and up-to-date.
To reinstall 2.3.8, run:
  brew reinstall gnupg
Warning: subversion 1.14.2_1 is already installed and up-to-date.
To reinstall 1.14.2_1, run:
  brew reinstall subversion

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Copying Craft Settings and Blueprint settings specific to building on macs.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Craft               : /Users/j/AstroRoot/craft-root
Version             : master
ABI                 : macos-clang-x86_64
Download directory  : /Users/j/AstroRoot/craft-root/download

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building INDI and required dependencies
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

arch: posix_spawnp: /opt/homebrew/opt/python@3.10/bin/python3.10: Bad CPU type in executable

**Comment by rlancaste** [comment]
Hi there, I am pretty sure this is not actually an issue with craft.  It appears to be an issue with the environment.  I think if you either need to install rosetta or configure your terminal to build in x86_64 instead of arm64.  A lot of programs and libraries are built using x86_64 and not everything has been ported to universal binaries or arm64 yet.   It is recommended by the Craft team to run the terminal in Rosetta for now until more things are universal or arm64 compatible.

Here's some references:
https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable
https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9

**Comment by JerryBlack** [comment]
Wow, thanks Rob for such a quick reply.
Launching Teminal using "Open using Rosetta" got by most of my issues I think.

Now grappling with ...
```
libgphoto2 requires the ltdl library, included with libtool

Please make sure that the proper development package is installed
(libltdl-dev, libtool-ltdl-devel, etc.)
```

But hopefully I can pick through that problem.

**Comment by rlancaste** [comment]
lib tool should be installed already in the craft directory

**Comment by rlancaste** [comment]
You could try ending the craft recipe for lib tool or rerunning it

Reinstall
cd ~/AstroRoot/craft-root/ ; source ~/AstroRoot/craft-root/craft/craftenv.sh
craft -vi libtool

Another option is to post in the craft forums to see if they know what's up
