### ISSUE TITLE
xplanet

### ISSUE THREAD

**Issue by Trigger-broom-289** [rlancaste/kstars-on-osx-craft#2]
In file included from /Users/heidenrod/AstroRoot/kstars-craft/build/libs/xplanet/work/xplanet-1.3.1/src/libannotate/addArcs.cpp:17:
In file included from /Users/heidenrod/AstroRoot/kstars-craft/build/libs/xplanet/work/xplanet-1.3.1/src/xpUtil.h:4:
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
13 errors generated.
make[3]: *** [addMarkers.o] Error 1
make[3]: *** [addArcs.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Action: compile for libs/xplanet:1.3.1 FAILED
*** Craft all failed: libs/xplanet after 25 seconds ***
fatal error: package libs/xplanet all failed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rlancaste** [comment]
Ok I just pushed a change to the craft recipes.  Can you test the script again?

**Comment by rlancaste** [comment]
I just tried another change to the recipe.  Can you try it again?

**Comment by rlancaste** [comment]
This is solved now by building xplanet separate from craft in the script
