### ISSUE TITLE
Rebuild fail under Catalina

### ISSUE THREAD

**Issue by astrobilluk** [rlancaste/kstars-on-osx-craft#3]
Just tried to rebuild KStars for MacOS under Catalina. My goal was really to just create new libraries for Altair Cameras in order to try to see if the latest SDK in the 3rd party area on GiutHUB enabled my camera, but suggestions elsewhere on how to do this were based on Linux scripts requiring root access to system files. While I gave myself root access the system area protection in Catalina defeated me. Jasem pointed me to your great MacOS script for the rebuild. I have installed Xcode, CLT, brew, Craft, Python. The master build script fell over at the point below. 

[5/90] Building C object CMakeFiles/cfitsio.dir/drvrnet.c.o
FAILED: CMakeFiles/cfitsio.dir/drvrnet.c.o 
/Library/Developer/CommandLineTools/usr/bin/clang -DCFITSIO_HAVE_CURL -DHAVE_NET_SERVICES -Dcfitsio_EXPORTS  -fdiagnostics-color=always -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -fPIC -MD -MT CMakeFiles/cfitsio.dir/drvrnet.c.o -MF CMakeFiles/cfitsio.dir/drvrnet.c.o.d -o CMakeFiles/cfitsio.dir/drvrnet.c.o   -c /Users/williamshaw/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c
/Users/williamshaw/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c:313:7: error: implicit declaration of function 'alarm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      alarm(0);
      ^
/Users/williamshaw/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c:346:5: error: implicit declaration of function 'alarm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    alarm(NETTIMEOUT*10);
    ^
/Users/williamshaw/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c:364:5: error: implicit declaration of function 'alarm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    alarm(NETTIMEOUT);
    ^
/Users/williamshaw/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c:380:3: error: implicit declaration of function 'alarm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  alarm(0);
  ^

and several further errors followed. I'm uncomfortable flagging this as an issue with your code as it might be my incompetence in setting up, but could not see how to contact you otherwise.  Jasem suggested there might be a new KStars build forthcoming to incoportate new SDKs from 3rd parties. As I am on a Mac I was keen to see if I could enable my Hypercam right away. Failing that the creation of a new MacOS build would be great. Thanks

**Comment by AirBourn** [comment]
I get the same results on OSX 10.15.7 and latest XCode 12 (Which changes location of CommandLine Tools).  Looks like the precompiler directives in drvrnet.c surrounding #include <unistd.h> aren't allowing the header to be included on OSX.  I tried editing drvrnet.c to solve, but script overwrites the file from a tar.gz archive during the build.

```
#if defined(unix) || defined(__unix__)  || defined(__unix) || defined(HAVE_UNISTD_H)
#include <unistd.h>  
#endif
```

**Comment by rlancaste** [comment]
Thank you very much for the comment,  sorry I haven't gotten to seeing what caused it yet  I'm rather busy at the moment making sure StellarSolver works in KStars.  But I will come back to this soon because I will need to do a complete rebuild on my Mac before making the DMG for 3.5.0. But for now I don't want to break my installation while I'm trying to perfect the library and its integration.

**Comment by AirBourn** [comment]
I noticed the Command-Line Tools updated again tonight.

**Comment by rlancaste** [comment]
I'm taking a look at this today.  My system is using Catalina, but I am using Xcode 11.  So far I have corrected several other issues, but I haven't encountered this issue.  Is it possible that I would encounter this if I upgrade to Xcode 12?

**Comment by astrobilluk** [comment]
I’m not knowledgeable enough on the latest Xcode to know the precise attribution of this problem. It may well be the new Xcode but it is possible the issue is elsewhere. Maybe prioritise getting a new KStars out then try a rebuild under Xcode 12?

**Comment by rlancaste** [comment]
Yes, that is my current plan, getting out an initial DMG for people to test for KStars 3.5.0 using my working setup first.

**Comment by AirBourn** [comment]
I'm not sure.  Last I tried was a month ago on a Catalina 10.15.7 machine.  If I recall correctly, I first tried XCode 11 and because it failed, first thing I did was update.  I suppose it's possible that code changes in the last month gave you different results?  I can try it again later today, I suppose.  I also have an El Capitan 10.11.6 machine with XCode 8, but I think that's too far behind to work. 

What's the latest doc and build script I should try?

**Comment by rlancaste** [comment]
El Capitan unfortunately is not supported by QT anymore.

**Comment by AirBourn** [comment]
Didn't get very far.  I did a new clone and pull and build-kstars.sh -r and brew failed with a page-and-a-half of errors on Astropy dependencies:

> `Collecting astropy
>   Using cached astropy-4.1.tar.gz (7.8 MB)
>   Installing build dependencies ... error
> 
>   ERROR: Command errored out with exit status 1:
> 
>    command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/5t/j1s3l2s55955nctv7__dm7_80000gn/T/pip-build-env-udbkq7lx/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel cython==0.29.14 jinja2==2.10.3 oldest-supported-numpy extension-helpers
>        cwd: None
> 
> ... goes on and on and on ...
> `

Interesting - saw this down in the weeds:  

> "$MACOSX_DEPLOYMENT_TARGET` mismatch: now "10.13" but "10.15" during configure"

I suspect it's got something to do with python and pip.  Stand by.

If I manually call out the pip install of astropy, it works fine:
`/usr/local/opt/python@3.9/libexec/bin/pip install astropy`

**Comment by AirBourn** [comment]
OK - after the manual install of astropy, the script runs fine as expected and dumps at the exact same place.  Looks like it's still the lack of `#include <unistd.h>` as reported above.

```
-- Build files have been written to: /Users/bryan/AstroRoot/craft-root/build/libs/cfitsio/work/build
executing command: "/Users/bryan/AstroRoot/craft-root/dev-utils/bin/ninja" 
[1/90] Building C object CMakeFiles/Fitscopy.dir/fitscopy.c.o
[2/90] Building C object CMakeFiles/Funpack.dir/funpack.c.o
[3/90] Building C object CMakeFiles/FPack.dir/fpack.c.o
[4/90] Building C object CMakeFiles/cookbook.dir/cookbook.c.o
[5/90] Building C object CMakeFiles/cfitsio.dir/checksum.c.o
[6/90] Building C object CMakeFiles/cfitsio.dir/buffers.c.o
[7/90] Building C object CMakeFiles/cfitsio.dir/drvrfile.c.o
[8/90] Building C object CMakeFiles/cfitsio.dir/drvrnet.c.o
FAILED: CMakeFiles/cfitsio.dir/drvrnet.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DCFITSIO_HAVE_CURL -DHAVE_NET_SERVICES -Dcfitsio_EXPORTS  -fdiagnostics-color=always -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -fPIC -MD -MT CMakeFiles/cfitsio.dir/drvrnet.c.o -MF CMakeFiles/cfitsio.dir/drvrnet.c.o.d -o CMakeFiles/cfitsio.dir/drvrnet.c.o   -c /Users/bryan/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c
/Users/bryan/AstroRoot/craft-root/build/libs/cfitsio/work/cfitsio/drvrnet.c:313:7: error: implicit declaration of function 'alarm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      alarm(0);
      ^
```

**Comment by astrobilluk** [comment]
I’m away from my dev Mac for a few days so not able to experiment sorry.

**Comment by rlancaste** [comment]
I am working on it today, I just removed astropy from the build since it's not required to be installed and I'm fixing a couple of the recipes that no longer work

**Comment by rlancaste** [comment]
I will push my changes to the repo after I verify that I fixed them

**Comment by rlancaste** [comment]
www.indilib.org/jdownloads/kstars/beta/kstars-3.5.0.dmg

**Comment by rlancaste** [comment]
I didn't encounter an issue with cfitsio, I am not sure why you did and I did not

**Comment by rlancaste** [comment]
It did print this as you stated, but it still built fine and it didn't stop anything.

drvrnet.c:1099:6: warning: implicit declaration of function 'alarm' is invalid in C99 [-Wimplicit-function-declaration]

**Comment by rlancaste** [comment]
ah there is a difference, mine says "warning" and yours says "error".

**Comment by rlancaste** [comment]
I suspect that somehow your system is enabling the flag -Werror, which would treat all warnings as errors.  But I don't see that flag in the craft recipe, nor do I see it in the source code for cfitsio.  But I do actually see it in the output you pasted above.  We can look into how that might have gotten set on your system.  it is odd if it happened on your system but not on mine.

**Comment by AirBourn** [comment]
Yeah - possibly a compiler or linker setting that's more restrictive in 12?  Not allowing implicit declarations without the header?

Did yours link after the warning?  If the compiler thinks that's a function declaration rather than a call, the linker may not know what to do with it because it doesn't know where the object code is?  I think you can solve the warning by assuring `unistd.h` is included.  There's a pre-compiler directive in the source, but I suspect the `#ifdefs` aren't catching it.  Maybe add a `defined(darwin)` to the `#ifdef`?

```
#if defined(unix) || defined(__unix__)  || defined(__unix) || defined(HAVE_UNISTD_H)
#include <unistd.h>  
#endif
```

**Comment by rlancaste** [comment]
So this code is in CFITSIO, which we don't have control over, I think that a change like this should be reported to them.  Can you send it to their developers?

**Comment by rlancaste** [comment]
If this is an Xcode 12 issue, and it sets this flag for all builds, then it will have big problems with astrometry.net, which has a ton of warnings like that.

**Comment by rlancaste** [comment]
I believe it linked up just fine after it finished.

**Comment by AirBourn** [comment]
> So this code is in CFITSIO, which we don't have control over, I think that a change like this should be reported to them. Can you send it to their developers?

I just downloaded CFITSIO 3.49 and did a ./configure and make.  I did get a lot of warnings, but no implicit dec errors and it did compile and link.  I've attached the term session log of the configure and make.  Maybe you can pick up something from the configure output?

I also notice that there's MacPorts and Homebrew installation support for CFITSIO - maybe change the recipe to install it with brew like others?

https://heasarc.gsfc.nasa.gov/fitsio/fitsio_macosx.html

[CFITSIO_Log.txt](https://github.com/rlancaste/kstars-on-osx-craft/files/5483740/CFITSIO_Log.txt)


Curiously, perusing through the original build output, I see this:
```
*** Handling package: libs/cfitsio, action: all ***
*** Action: fetch-binary for libs/cfitsio ***
Could not find libs/cfitsio=3.45 in https://files.kde.org/craft/master/Qt_5.15.1/macos/64/clang/RelWithDebInfo
Could not find libs/cfitsio=3.45 in https://files.kde.org/craft/master/Qt_5.15.1/macos/64/clang/Release
*** libs/cfitsio not found in cache ***
```

**Comment by simont77** [comment]
Hi, would it be possible to update also the libgphoto included in kstars for Mac? If I understood well your script, it is still downloading version 2.5.24, we are now at 2.5.26.

**Comment by rlancaste** [comment]
Yep!

**Comment by rlancaste** [comment]
Ok I think I may have just corrected the Xcode 12 build issue by adding an environment variable to not treat this warning as an error. I don't know why the default behavior changed, but we can put a band-aid on it to prevent it from being a problem.  Please try it out!

**Comment by AirBourn** [comment]
I thought you had it!  Definitely got past the cfitsio compile.  Ran for a long time and finally failed here:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Getting Oxygen Sounds for KStars
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cloning into 'oxygen'...
remote: Enumerating objects: 331, done.
remote: Counting objects: 100% (331/331), done.
remote: Compressing objects: 100% (265/265), done.
remote: Total 26486 (delta 189), reused 179 (delta 64), pack-reused 26155
Receiving objects: 100% (26486/26486), 10.70 MiB | 8.48 MiB/s, done.
Resolving deltas: 100% (15451/15451), done.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building KStars and required dependencies
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

KShimgen 0.4.3: KShim: posix_spawn: No such file or directory

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rlancaste** [comment]
Aw man. I think this is a mistake in craft.  I found a couple of them just now.  I will email Hannah.

**Comment by lantictac** [comment]
I've just run into the same issue:

`KShimgen 0.4.3: KShim: posix_spawn: No such file or directory`

Any news?

Thanks a million for all the work on this btw :)

**Comment by rlancaste** [comment]
Actually yesterday I just figured out what caused this.  It doesn’t happen all the time but when it does it wasn’t clear what caused it.  It’s an out of date script in craft referencing older versions of python.  If you open the ~/astroroot/craft/craftenv.sh file and edit where it is searching for which version of python is installed, you can change it from 3.7 to 3.9 (at least mine is 3.9) and then craft works fine.

**Comment by lantictac** [comment]
Great! Thanks so much. I'll give it a whirl just now...

**Comment by lantictac** [comment]
Thanks again. I can confirm that fixing the Python lookup in craftenv.sh fixed the issue for me:

```
if command -v python3.9 >/dev/null; then
    CRAFT_PYTHON_BIN=$(command -v python3.9)
elif command -v python3.7 >/dev/null; then
    [...]
```

I also had to manually fix an issue in craft/bin/Source/VersionSystemSourceBase.py in `sourceDir(self, index=0)` when `self.checkoutDir(index)` returns a str rather than a Path - this causes `sourcedir = sourcedir / self.subinfo.targetSourcePath()` to fail since '/' isn't a valid operator for an str.

I worked around it by always constructing a Path object: `sourcedir = Path(self.checkoutDir(index))`

**Comment by rlancaste** [comment]
Actually it is possible that the issue finding python was because I was calling the crafting.sh twice.  Either way, changing that to 3.9 is not a bad thing.

The Path object issue you mentioned is a craft bug that I emailed them about several times already.  Hopefully they fix it soon.
