### ISSUE TITLE
Build failed on High Sierra

### ISSUE THREAD

**Issue by Trigger-broom-289** [rlancaste/kstars-on-osx-craft#4]
Hello Rob,

I'm getting the following issue:

In file included from /Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/stream/recorder/recordermanager.cpp:29:
/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/stream/recorder/theorarecorder.h:26:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
[23/454] Building C object CMakeFiles/indidriverstatic.dir/libs/stream/ccvt_misc.c.o
[24/454] Building C object CMakeFiles/indidriverstatic.dir/libs/stream/jpegutils.c.o
[25/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/recorder/serrecorder.cpp.o
[26/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/streammanager.cpp.o
[27/454] Building CXX object CMakeFiles/indi_planewave_deltat.dir/drivers/auxiliary/planewave_delta.cpp.o
ninja: build stopped: subcommand failed.
Action: compile for libs/indiserver:Latest FAILED
*** Craft all failed: libs/indiserver after 1 minute 32 seconds ***
fatal error: package libs/indiserver all failed
Craft stopped with out completing ['libs/indiserver']

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Stephane

**Comment by Trigger-broom-289** [comment]
Update:
it seems to be going after I ran this command:
**brew link libogg**

**Comment by Trigger-broom-289** [comment]
Update:
it failed again...

[190/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/recorder/recordermanager.cpp.o
FAILED: CMakeFiles/indidriverstatic.dir/libs/stream/recorder/recordermanager.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/clang++  -DGIT_TAG_STRING=\"v1.8.6-39-gbbcea2be\" -DHAVE_LIBNOVA -DWITH_ENCLEN -I. -I/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver -I/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs -I/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/indibase -I/Users/heidenrod/AstroRoot/craft-root/include -I/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/dsp -I/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/stream -I/Users/heidenrod/AstroRoot/craft-root/include/libnova -I/Users/heidenrod/AstroRoot/craft-root/include/libusb-1.0 -fdiagnostics-color=always -std=c++11 -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE -O1  -Wall -Wextra -Wno-nonnull -Wno-deprecated-declarations -g -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13   -fPIC -MD -MT CMakeFiles/indidriverstatic.dir/libs/stream/recorder/recordermanager.cpp.o -MF CMakeFiles/indidriverstatic.dir/libs/stream/recorder/recordermanager.cpp.o.d -o CMakeFiles/indidriverstatic.dir/libs/stream/recorder/recordermanager.cpp.o -c /Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/stream/recorder/recordermanager.cpp
In file included from /Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/stream/recorder/recordermanager.cpp:29:
/Users/heidenrod/AstroRoot/craft-root/download/git/libs/indiserver/libs/stream/recorder/theorarecorder.h:26:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
[191/454] Building C object CMakeFiles/indidriverstatic.dir/libs/stream/jpegutils.c.o
[192/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/encoder/encodermanager.cpp.o
[193/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/recorder/serrecorder.cpp.o
[194/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/stream/streammanager.cpp.o
[195/454] Building CXX object CMakeFiles/indidriverstatic.dir/libs/indibase/dsp/dspinterface.cpp.o
ninja: build stopped: subcommand failed.
Action: compile for libs/indiserver:Latest FAILED
*** Craft all failed: libs/indiserver after 2 minutes 1 second ***
fatal error: package libs/indiserver all failed
Craft stopped with out completing ['libs/indiserver']

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rlancaste** [comment]
Thank you very much for the comment,  sorry I haven't gotten to seeing what caused it yet  I'm rather busy at the moment making sure StellarSolver works in KStars.  But I will come back to this soon because I will need to do a complete rebuild on my Mac before making the DMG for 3.5.0. But for now I don't want to break my installation while I'm trying to perfect the library and its integration.

**Comment by Trigger-broom-289** [comment]
Hello Rob,

No worries, concentrate on StellarSolver first it's a kick ass tool. I'll wait for 3.5.0 👍

**Comment by simont77** [comment]
Hi, would it be possible to update also the libgphoto included in kstars for Mac? If I understood well your script, it is still downloading version 2.5.24, we are now at 2.5.26.
