### ISSUE TITLE
Issue Building INDI 3rd Party Libraries and required dependencies - libs/pcreTest

### ISSUE THREAD

**Issue by JerryBlack** [rlancaste/kstars-on-osx-craft#6]
Hopefully it's not just me and something has changed, but I'm getting a missing libs/pcreTest during the craft execution

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Building INDI 3rd Party Libraries and required dependencies
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Craft               : /Volumes/Data_Raid/AstroRoot/craft-root
Version             : master
ABI                 : macos-64-clang
Download directory  : /Volumes/Data_Raid/AstroRoot/craft-root/download
================================================================================
*** Handling package: libs/pcreTest, action: all ***
*** Action: fetch-binary for libs/pcreTest ***
Could not find libs/pcreTest=8.45 in https://files.kde.org/craft/master/Qt_5.15.2-4/macos/64/clang/RelWithDebInfo
Could not find libs/pcreTest=8.45 in https://files.kde.org/craft/master/Qt_5.15.2-4/macos/64/clang/Release
*** libs/pcreTest not found in cache ***
*** Action: fetch for libs/pcreTest ***
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   276    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

executing command: /usr/bin/curl -C - --retry 10 -L --ftp-ssl --fail --cacert /Volumes/Data_Raid/AstroRoot/craft-root/etc/cacert.pem --max-redirs 50 -o /Volumes/Data_Raid/AstroRoot/craft-root/download/archives/libs/pcreTest/pcreTest-8.45.tar.gz https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.bz2 -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 131.111.8.88:443...
* Connected to ftp.pcre.org (131.111.8.88) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /Volumes/Data_Raid/AstroRoot/craft-root/etc/cacert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [226 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ftp.pcre.org:443 
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ftp.pcre.org:443 
Action: fetch for libs/pcreTest:8.45 FAILED
*** Craft all failed: libs/pcreTest after 12 seconds ***
fatal error: package libs/pcreTest all failed
Craft stopped with out completing ['libs/pcreTest', 'libs/swig', 'libs/libftdi', 'libs/libdc1394', 'libs/jasper', 'libs/lcms2', 'libs/libraw', 'libs/tiff', 'libs/liblame', 'libs/libopus', 'libs/libsamplerate', 'libs/libsdl2', 'libs/libogg', 'libs/libvorbis', 'libs/pthreads', 'libs/libvpx', 'libs/x264', 'libs/x265', 'libs/ffmpeg', 'libs/librtlsdr', 'libs/indiserver3rdPartyLibraries']

```
Thanks

**Comment by rlancaste** [comment]
That sounds to me like an issue on their server.  You might try again later and see if it clears up.

**Comment by JerryBlack** [comment]
I tried a number of times, but today found this http://www.pcre.org/ which suggests the ftp site is no longer available.... 

Download

You can download the current release of the PCRE2 library from its official home on GitHub:

    https://github.com/PhilipHazel/pcre2/releases

You can also download PCRE2 or the older, unmaintained PCRE library from an unofficial mirror at SourceForge:

    https://sourceforge.net/projects/pcre/files/

You can check out the PCRE2 source code via Git or Subversion:

    git clone https://github.com/PhilipHazel/pcre2.git

Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

I'm not sure how to tweak the craft install to make this substitution.

Thanks

**Comment by rlancaste** [comment]
Yes, I came to the same conclusion, it is no longer going to be available from the same website.  I think I updated each of the craft recipes for PCRE and PCRE2 to use the new address.  I am not sure if you tried it before or after I made the changes.  Here's my recipes.  If you note, I think the change was made awhile ago.  Did I miss one of them?

**Comment by rlancaste** [comment]
Yep, I may have missed one, please check again, I just updated the other one.

**Comment by JerryBlack** [comment]
Hi, OK, I believe I erased my  kstars-on-osx-craft directory, and started with a fresh git.
```
...
*** Action: post-install for libs/libgphoto2 ***
*** Action: qmerge for libs/libgphoto2 ***
*** Action: post-qmerge for libs/libgphoto2 ***
*** Craft all succeeded: libs/libgphoto2 after 1 minute 8 seconds ***
==================================================================================================================================================================================
*** Handling package: libs/pcreTest, action: all ***
*** Action: fetch-binary for libs/pcreTest ***
Could not find libs/pcreTest=8.45 in https://files.kde.org/craft/master/21.12/macos/64/clang/RelWithDebInfo
Could not find libs/pcreTest=8.45 in https://files.kde.org/craft/master/21.12/macos/64/clang/Release
*** libs/pcreTest not found in cache ***
*** Action: fetch for libs/pcreTest ***
executing command: /usr/bin/curl -C - --retry 10 -L --ftp-ssl --fail --cacert /Users/jerryblack/Volumes/Data_Raid/AstroRoot/craft-root/etc/cacert.pem --max-redirs 50 -o /Users/jerryblack/Volumes/Data_Raid/AstroRoot/craft-root/download/archives/libs/pcreTest/pcreTest-8.45.tar.gz  https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2 -v
* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL
Action: fetch for libs/pcreTest:8.45 FAILED
*** Craft all failed: libs/pcreTest after 0 seconds ***
fatal error: package libs/pcreTest all failed
Craft stopped with out completing ['libs/pcreTest', 'libs/swig', 'libs/libftdi', 'libs/libdc1394', 'libs/jasper', 'libs/lcms2', 'libs/libraw', 'libs/tiff', 'libs/liblame', 'libs/libopus', 'libs/libsamplerate', 'libs/libsdl2', 'libs/libogg', 'libs/libvorbis', 'libs/pthreads', 'libs/libvpx', 'libs/x264', 'libs/x265', 'libs/ffmpeg', 'libs/librtlsdr', 'libs/indiserver3rdPartyLibraries']

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ Something failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
full text at https://www.dropbox.com/s/kqj5ecver73dl5k/kstars-on-osx-craft_output.txt?dl=0

**Comment by rlancaste** [comment]
Sorry, you are right, I had an issue in the URL.  I didn't detect it when I tested it because I had the file already downloaded in my "archives". Please try again.

**Comment by JerryBlack** [comment]
Same result as above, with a newly downloaded git. I also tested building directly to the default location (rather than an external volume via a modified build-env.sh) with the same result.  Hmm.

**Comment by rlancaste** [comment]
Ok I think I figured it out.  There was a space in the URL.  Please try now, sorry for the issue.

**Comment by JerryBlack** [comment]
OK, no problem, glad I can assist in a small way to debug.   On the 2nd attempt, it compiled successfully!
3.5.7 Beta
Build: 2021-12-24T12:59:51Z

Thank you!    (didnt' try the DMG  stuff or webmanager yet)

**Comment by JerryBlack** [comment]
I tried a number of times, but today found this http://www.pcre.org/ which suggests the ftp site is no longer available.... 

Download

You can download the current release of the PCRE2 library from its official home on GitHub:

    https://github.com/PhilipHazel/pcre2/releases

You can also download PCRE2 or the older, unmaintained PCRE library from an unofficial mirror at SourceForge:

    https://sourceforge.net/projects/pcre/files/

You can check out the PCRE2 source code via Git or Subversion:

    git clone https://github.com/PhilipHazel/pcre2.git

Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

I'm not sure how to tweak the craft install to make this substitution.

Thanks
