### ISSUE TITLE
libwcs.dylib missing (though libwcs.7.2.dylib was created)

### ISSUE THREAD

**Issue by castorf** [rlancaste/kstars-on-osx-craft#9]
I haven't drilled down into this, but just setting up a symlink seems to have let things go further.

**Comment by rlancaste** [comment]
You might want to start with a fresh AstroRoot directory.  I have made a lot of changes in the last 2 weeks.  The goal is to get my recipes integrated into craft so that we can use craft to build.  libwcs has already been integrated.  We are now using craft's recipe for that.

**Comment by castorf** [comment]
I started with a fresh AstroRoot directory, and am still getting build errors.  Now in libs/stellarsolver   It looks like maybe a libz problem?

[103/104] Linking CXX shared library libstellarsolver.1.8.dylib
FAILED: libstellarsolver.1.8.dylib
: && /Library/Developer/CommandLineTools/usr/bin/clang++ -fdiagnostics-color=always -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -Wl,-rpath,/Users/castor/AstroRoot/craft-root/lib   -compatibility_version 1.0.0 -current_version 1.8.0 -o libstellarsolver.1.8.dylib -install_name @rpath/libstellarsolver.1.dylib CMakeFiles/stellarsolver.dir/stellarsolver_autogen/mocs_compilation.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/parameters.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sextractorsolver.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/internalsextractorsolver.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/externalsextractorsolver.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/onlinesolver.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/stellarsolver.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/analyse.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/aperture.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/background.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/convolve.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/deblend.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/extract.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/lutz.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/sep/util.cpp.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/engine.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/blindutils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/blind.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/solver.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/quad-utils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/matchfile.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/matchobj.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/solvedclient.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/solvedfile.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/tweak2.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/verify.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/blind/tweak.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/multiindex.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/index.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/codekd.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/starkd.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/rdlist.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/xylist.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/starxy.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/qidxfile.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/quadfile.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/scamp.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/scamp-catalog.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/wcs-xy2rd.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/wcs-rd2xy.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/sip-utils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/fit-wcs.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/sip.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/anwcs.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/wcs-resample.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/gslutils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/wcs-pv2sip.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/fitsioutils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/sip_qfits.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/fitstable.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/fitsbin.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/fitsfile.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/tic.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/starutil.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/mathutil.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/bl-sort.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/bl.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/bt.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/healpix-utils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/healpix.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/permutedsort.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/ioutils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/fileutils.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/os-features.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/an-endian.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/errors.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/log.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/datalog.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/sparsematrix.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/coadd.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/convolve-image.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/resample.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/intmap.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/histogram.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/util/histogram2d.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdint_ddd.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdint_fff.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdint_ddu.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdint_duu.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdint_dds.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdint_dss.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdtree.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdtree_dim.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdtree_mem.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/kdtree_fits_io.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/dualtree.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/dualtree_rangesearch.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/libkd/dualtree_nearestneighbour.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/anqfits.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_card.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_convert.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_error.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_header.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_image.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_table.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_time.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_tools.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_byteswap.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_memory.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_rw.c.o CMakeFiles/stellarsolver.dir/stellarsolver/astrometry/qfits-an/qfits_float.c.o  -Wl,-rpath,/Users/castor/AstroRoot/craft-root/lib  /Users/castor/AstroRoot/craft-root/lib/libcfitsio.a  /Users/castor/AstroRoot/craft-root/lib/libgsl.dylib  /Users/castor/AstroRoot/craft-root/lib/libgslcblas.dylib  /Users/castor/AstroRoot/craft-root/lib/libwcslib.a  /Users/castor/AstroRoot/craft-root/lib/QtNetwork.framework/QtNetwork  /Users/castor/AstroRoot/craft-root/lib/QtWidgets.framework/QtWidgets  /Users/castor/AstroRoot/craft-root/lib/QtConcurrent.framework/QtConcurrent  -lpthread  /Users/castor/AstroRoot/craft-root/lib/QtGui.framework/QtGui  /Users/castor/AstroRoot/craft-root/lib/QtCore.framework/QtCore && :
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      _compress2mem_from_mem in libcfitsio.a(zcompress.c.o)
      _compress2file_from_mem in libcfitsio.a(zcompress.c.o)
  "_deflateEnd", referenced from:
      _compress2mem_from_mem in libcfitsio.a(zcompress.c.o)
      _compress2file_from_mem in libcfitsio.a(zcompress.c.o)
  "_deflateInit2_", referenced from:
      _compress2mem_from_mem in libcfitsio.a(zcompress.c.o)
      _compress2file_from_mem in libcfitsio.a(zcompress.c.o)
  "_inflate", referenced from:
      _uncompress2mem in libcfitsio.a(zcompress.c.o)
      _uncompress2mem_from_mem in libcfitsio.a(zcompress.c.o)
      _uncompress2file in libcfitsio.a(zcompress.c.o)
  "_inflateEnd", referenced from:
      _uncompress2mem in libcfitsio.a(zcompress.c.o)
      _uncompress2mem_from_mem in libcfitsio.a(zcompress.c.o)
      _uncompress2file in libcfitsio.a(zcompress.c.o)
  "_inflateInit2_", referenced from:
      _uncompress2mem in libcfitsio.a(zcompress.c.o)
      _uncompress2mem_from_mem in libcfitsio.a(zcompress.c.o)
      _uncompress2file in libcfitsio.a(zcompress.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Action: compile for libs/stellarsolver:master FAILED
*** Craft all failed: libs/stellarsolver after 33 seconds ***
fatal error: package libs/stellarsolver all failed
Craft stopped with out completing ['libs/stellarsolver', 'qt-libs/qtkeychain', 'kde/applications/ksta

**Comment by rlancaste** [comment]
Yes this one I expected, since someone made a change to a recipe the other day that breaks our build.  But it’s an easy fix.  Please see this thread for the solution 

https://github.com/rlancaste/kstars-on-osx-craft/issues/8

**Comment by JerryBlack** [comment]
As of 2022/01/11 a complete reinstall (not sure if that was a requirement)  has solved this problem for me. Thanks!
